apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: audioseeker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: yc-registry-secret
      containers:
        - name: backend
          image: cr.yandex/crp72ttqt6p7du7uvurg/audio-seeker-backend:lab3
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"