sonar.projectKey=audioseeker
sonar.projectName=audioseeker

sonar.sources=back,frontend/src

sonar.python.coverage.reportPaths=back/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.exclusions=**/.coverage,**/.coverage.*,**/coverage.xml,**/dev/**,**/.venv/**,**/venv/**,**/__pycache__/**,**/node_modules/**,**/.git/**
sonar.coverage.exclusions=**/tests/**,**/test_*.py,**/*_test.py,**/__test__/**,back/test/**
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=900